version: 2
registries:
  npm-registry-ezcater-jfrog-io-ezcater-api-npm-npm:
    type: npm-registry
    url: https://ezcater.jfrog.io/ezcater/api/npm/npm
    username: "${{secrets.NPM_REGISTRY_EZCATER_JFROG_IO_EZCATER_API_NPM_NPM_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_EZCATER_JFROG_IO_EZCATER_API_NPM_NPM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: i18next
    versions:
    - 19.8.5
    - 19.8.7
    - 19.8.8
    - 19.8.9
    - 19.9.0
    - 19.9.1
    - 19.9.2
    - 20.0.0
    - 20.1.0
    - 20.2.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  registries:
  - npm-registry-ezcater-jfrog-io-ezcater-api-npm-npm
